# Generated by Django 3.0.4 on 2020-04-29 10:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200404_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 29, 10, 24, 24, 319126, tzinfo=utc)),
        ),
    ]
